# GenerateDockerfile.cmake
# Standalone CMake script that generates a Dockerfile.deps with pre-cached dependencies.
#
# Usage:
#   cmake -DDEPS_DIR=cmake/litergss-app/dependencies \
#         -DBASE_DOCKERFILE=docker/Dockerfile \
#         -DOUTPUT_DIR=build/docker \
#         -P cmake/docker/GenerateDockerfile.cmake
#
# The generated Dockerfile.deps:
#   - Extends the base Dockerfile (multi-stage)
#   - Pre-downloads all URL-based dependencies into /opt/deps-cache/downloads/
#   - Pre-clones all git-based dependencies into /opt/deps-cache/git/
#
# The build system picks up the cache via BUILD_DOWNLOAD_DIR for URL deps.

cmake_minimum_required(VERSION 3.16)

# Validate required parameters
if(NOT DEFINED DEPS_DIR)
    message(FATAL_ERROR "DEPS_DIR is required. Usage: cmake -DDEPS_DIR=<path> -DBASE_DOCKERFILE=<path> -DOUTPUT_DIR=<path> -P GenerateDockerfile.cmake")
endif()
if(NOT DEFINED BASE_DOCKERFILE)
    message(FATAL_ERROR "BASE_DOCKERFILE is required")
endif()
if(NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "OUTPUT_DIR is required")
endif()

# Make paths absolute relative to the working directory
if(NOT IS_ABSOLUTE "${DEPS_DIR}")
    set(DEPS_DIR "${CMAKE_SOURCE_DIR}/${DEPS_DIR}")
endif()
if(NOT IS_ABSOLUTE "${BASE_DOCKERFILE}")
    set(BASE_DOCKERFILE "${CMAKE_SOURCE_DIR}/${BASE_DOCKERFILE}")
endif()
if(NOT IS_ABSOLUTE "${OUTPUT_DIR}")
    set(OUTPUT_DIR "${CMAKE_SOURCE_DIR}/${OUTPUT_DIR}")
endif()

# Include the parsing module
include(${CMAKE_CURRENT_LIST_DIR}/ParseDependencies.cmake)

# Parse all dependencies
parse_all_dependencies("${DEPS_DIR}")
message(STATUS "Found ${DEP_COUNT} dependencies")

# Read the base Dockerfile
file(READ "${BASE_DOCKERFILE}" BASE_DOCKERFILE_CONTENT)

# Generate download commands
set(DOWNLOAD_COMMANDS "")
set(GIT_CLONE_COMMANDS "")
set(URL_DEP_COUNT 0)
set(GIT_DEP_COUNT 0)

math(EXPR LAST_IDX "${DEP_COUNT} - 1")
foreach(I RANGE 0 ${LAST_IDX})
    if(DEP_${I}_TYPE STREQUAL "url")
        message(STATUS "  [url] ${DEP_${I}_NAME} ${DEP_${I}_VERSION}: ${DEP_${I}_FILENAME}")
        # Extract hash value for verification comment
        set(HASH_COMMENT "")
        if(DEP_${I}_HASH)
            set(HASH_COMMENT " # ${DEP_${I}_HASH}")
        endif()
        string(APPEND DOWNLOAD_COMMANDS "    wget -q -O /opt/deps-cache/downloads/${DEP_${I}_FILENAME} \"${DEP_${I}_URL}\" && \\
    echo \"  Downloaded: ${DEP_${I}_NAME} ${DEP_${I}_VERSION}\" && \\\n")
        math(EXPR URL_DEP_COUNT "${URL_DEP_COUNT} + 1")
    elseif(DEP_${I}_TYPE STREQUAL "git")
        set(SHALLOW_FLAG "")
        if(NOT DEP_${I}_GIT_TAG STREQUAL "HEAD" AND NOT DEP_${I}_GIT_TAG MATCHES "^[a-f0-9]+$")
            set(SHALLOW_FLAG " --depth 1 --branch ${DEP_${I}_GIT_TAG}")
        else()
            set(SHALLOW_FLAG " --depth 1")
        endif()
        message(STATUS "  [git] ${DEP_${I}_NAME} ${DEP_${I}_VERSION}: ${DEP_${I}_GIT_URL} @ ${DEP_${I}_GIT_TAG}")
        string(APPEND GIT_CLONE_COMMANDS "    git clone${SHALLOW_FLAG} ${DEP_${I}_GIT_URL} /opt/deps-cache/git/${DEP_${I}_NAME} && \\
    echo \"  Cloned: ${DEP_${I}_NAME} ${DEP_${I}_VERSION}\" && \\\n")
        math(EXPR GIT_DEP_COUNT "${GIT_DEP_COUNT} + 1")
    endif()
endforeach()

# Build the generated Dockerfile
set(DOCKERFILE_CONTENT "")

# Comment header
string(APPEND DOCKERFILE_CONTENT "\
# =============================================================================
# Dockerfile.deps - Auto-generated by cmake/docker/GenerateDockerfile.cmake
# DO NOT EDIT MANUALLY - regenerate with: make docker-deps-image
#
# This Dockerfile extends the base image and pre-caches all dependency
# downloads (tarballs + git repos) so builds skip the download phase.
#
# Dependencies extracted from: cmake/litergss-app/dependencies/*.cmake
#   URL dependencies: ${URL_DEP_COUNT}
#   Git dependencies: ${GIT_DEP_COUNT}
# =============================================================================

")

# Include base Dockerfile content inline (so the generated file is self-contained)
string(APPEND DOCKERFILE_CONTENT "${BASE_DOCKERFILE_CONTENT}\n")

# Add dependency download layer
if(URL_DEP_COUNT GREATER 0)
    string(APPEND DOCKERFILE_CONTENT "\
# =============================================================================
# Pre-download URL-based dependencies
# =============================================================================
RUN mkdir -p /opt/deps-cache/downloads && \\
${DOWNLOAD_COMMANDS}    echo \"All URL dependencies downloaded (${URL_DEP_COUNT} archives)\"

")
endif()

if(GIT_DEP_COUNT GREATER 0)
    string(APPEND DOCKERFILE_CONTENT "\
# =============================================================================
# Pre-clone git-based dependencies
# =============================================================================
RUN mkdir -p /opt/deps-cache/git && \\
${GIT_CLONE_COMMANDS}    echo \"All git dependencies cloned (${GIT_DEP_COUNT} repos)\"

")
endif()

# Add a label with generation metadata
string(TIMESTAMP GEN_TIMESTAMP "%Y-%m-%dT%H:%M:%S" UTC)
string(APPEND DOCKERFILE_CONTENT "\
# Metadata
LABEL deps.generated=\"${GEN_TIMESTAMP}\" \\
      deps.url_count=\"${URL_DEP_COUNT}\" \\
      deps.git_count=\"${GIT_DEP_COUNT}\"
")

# Write the output
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(OUTPUT_FILE "${OUTPUT_DIR}/Dockerfile.deps")
file(WRITE "${OUTPUT_FILE}" "${DOCKERFILE_CONTENT}")

message(STATUS "")
message(STATUS "Generated: ${OUTPUT_FILE}")
message(STATUS "  URL deps: ${URL_DEP_COUNT}")
message(STATUS "  Git deps: ${GIT_DEP_COUNT}")
message(STATUS "")
message(STATUS "To build the image:")
message(STATUS "  docker build -f ${OUTPUT_FILE} -t litergss-deps docker/")
message(STATUS "")
message(STATUS "Or use: make docker-deps-image")
